name: Publish

on:
  push:
    branches: [master]
    tags: ['*']

jobs:
  publish-scm-1:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup cjson
        run: luarocks install --local lua-cjson

      - name: Upload rockspec scm-1
        run: luarocks upload --force --api-key=${{ secrets.LUAROCKS_API_KEY }} molly-scm-1.rockspec

  publish-tag:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    env:
      TAG: ${GITHUB_REF##*/}
    steps:
      # https://github.com/luarocks/luarocks/wiki/Types-of-rocks
      - uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup cjson
        run: luarocks install --local lua-cjson

      - name: Make a release
        run: |
          luarocks new_version --tag ${{ env.TAG }}
          luarocks install --local molly-${{ env.TAG }}-1.rockspec
          luarocks pack molly-${{ env.TAG }}-1.rockspec

      - name: Upload .rockspec and .src.rock
        run: |
            luarocks upload --api-key=${{ secrets.LUAROCKS_API_KEY }} molly-${{ env.TAG }}-1.rockspec molly-${{ env.TAG }}-1.src.rock

  publish-ldoc:
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - name: Clone the module
        uses: actions/checkout@v3

      - name: Setup luarocks
        run: sudo apt install -y luarocks

      - name: Setup dependencies
        run: make deps-dev

      - run: echo $(luarocks path --lr-bin) >> $GITHUB_PATH

      - name: Build documentation with LDoc
        run: make doc

      - name: Publish generated API documentation to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: doc/html
